swagger: "2.0"
info:
  version: "0.0.1"
  title: UOIT Room Finder API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /classes:
    # binds a127 app logic to a route
    x-swagger-router-controller: classes
    get:
      description: Returns empty classrooms for the given date and time
      # used as the method name of the controller
      operationId: getClassesByParam
      parameters:
        - name: date
          in: query
          description: The date you want to find empty classrooms in (YYYY-MM-DD) format
          required: true
          type: string
        - name: start_time
          in: query
          description: Start of the time range in which you are searching for empty classrooms in (HH:mm:ss) format
          required: false 
          type: string
        - name: end_time
          in: query
          description: End of the time range in which you are searching for empty classrooms in (HH:mm:ss) format
          required: false 
          type: string
        - name: building
          in: query
          description: Filter empty classrooms by building
          required: false 
          type: string
      responses:
        "200":
          description: An array of Class objects
          schema:
            $ref: "#/definitions/Class"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /futureClasses:
    # binds a127 app logic to a route 
    x-swagger-router-controller: classes
    get: 
      description: Returns the next classes occuring in a specified room after a certain time
      # used as the method name of the controller 
      operationId: getFutureClasses
      parameters:
        - name: room
          in: query 
          description: The room you want to see future classes for 
          required: true 
          type: string
        - name: date
          in: query
          description: The date you want to see the classes for 
          required: true
          type: string
        - name: start_time
          in: query
          description: The start of the time range in which you are searching for future classes
          required: false
          type: string
      responses:
        "200":
          description: An array of Class objects
          schema:
            $ref: "#/definitions/Class"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /roomSchedule:
      # binds a127 app logic to a route 
      x-swagger-router-controller: classes
      get: 
        description: Returns the next classes occuring in a specified room after a certain time
        # used as the method name of the controller 
        operationId: getRoomSchedule
        parameters:
          - name: room
            in: query 
            description: The room you want to see future classes for 
            required: true 
            type: string
        responses:
          "200":
            description: An array of Class objects
            schema:
              $ref: "#/definitions/Class"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw

definitions:
  # complex objects have schema definitions
  Class:
    type: object
    properties:
      room:
        type: string
        example: UA1350
      building: 
        type: string
        example: Science Building (UA)
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
